resource_group_name     = "apprg"
resource_group_location = "eastus"
app_service_plan_name   = "myplan"
app_service_name        = "appservice"
sql_server_name         = "appserver"
sql_database_name       = "phpapp"
sql_admin_password      = "soumya@1987"
storage_acc_name        = "appsdeploy87"